### ISSUE TITLE
代码重构

### ISSUE THREAD

**Issue by sunxiansong** [lomocoin/wallet-core#12]
### 现有代码存在的问题：

- 总的来说，sdk面向多币种HD钱包设计，接口比较固定不容易拓展
- 代码、功能耦合比较严重，全部揉在一个工程里，单独使用某些特性甚至不太可能。例如：
    - 现在的代码必须使用HD 私钥推导方案，无法直接使用私钥（不排除有人不想用HD私钥推导方案的）
    - 只用一个币种也必须使用多币种的接口
- 单个币种难以增加自己特有的特性，难以调和通用接口和专有特性的平衡，单币种无法进行细粒度的控制
- package内依赖存在不合理的地方
- go 导出到移动端可用的类型存在限制，使用不支持的数据类型需要对类型进行包装，目前各模块都有导出包装的类型，不统一。

---

### 主要目标：

- 优化、重新设计多币种接口，使更合理、易于拓展
- 具备明显边界特征的单个模块、特性可以单独引用而不会导入其他模块的依赖(比如，可以独立使用btc模块、bip39/bip44模块、eth模块)，单个模块可以直接导出到移动端使用，单个模块导出体积尽可能小
- 单币种应该可以进行细粒度的控制，容易的添加新特性
- 在以上目标下可以轻松的导出到React Native 或 Flutter 
- 可以容易的加入新币种

### 次要目标：

- 单个币种接口设计上向官方RPC用法靠拢，降低学习成本
- 减小打包体积（目前安卓18M，单个模块目标体积应该尽可能小）
- 时间充裕的话可以考虑封装到ReactNative/Flutter依赖

---

### 实施方案、步骤

1. 处理现有PR到dev分支，从dev分支拉出重构分支，在重构分支上进行重构后合并到dev分支
2. 重新组织目录，按照下述约定组织
```
|- gmtypes go mobile types,统一包装通用的go 类型以支持导出到移动端使用
|- core 币种目录，每个币种一个目录，该目录下放币种需要实现的接口，
    |- btc 比特币实现
        |- internal 不需要导出的实现
    |- omni USDT实现
    |- eth 以太坊/erc20实现
|- bip39
|- bip44
|- coins 或者 wallet 通用币种接口
```
3. 把BTC、ETH按照新的目录重构，并测试

---

### 关于测试

每个币种（包括代币）的核心功能至少需要测试链验证，至少需要支持半自动化测试

**Comment by Aimeelu668** [comment]
通过API直接对接优盾钱包就很省事了，全token支持，多地址、余额一键归集
